image:
  repository: mysql # postgres or mysql
  tag: 8 # For mysql
#  tag: 16-alpine # For postgres
  pullPolicy: IfNotPresent


storage:
  enabled: true
  class: ~
  accessModes: ReadWriteOnce
  dataSize: 1Gi
  # -- Use an existing PersistentVolumeClaim, overrides values above
  existingClaim: ""

extraVolumeMounts: []
extraVolumes: []

restore:
  enabled: false

backupHelmHooks: false
backup:
  # There are two possible backup destinations currently implemented, http and pvc
  destination: http
  gzip: true
  filename: $DB_NAME-`date +%Y%m%d%H%M%S`.sql.gz
  # Persistence
  pvc:
    enabled: false
    class: ~
    accessModes: ReadWriteOnce
    dataSize: 1Gi
    # -- Use an existing PersistentVolumeClaim, overrides values above
    existingClaim: ""
  extraVolumeMounts: []
  extraVolumes: []

backupSchedule: "0 3 * * *"

global:
  config:
    env:
      RESTORE_URL: ""
      BACKUP_URL: ""
      DB_CONNECTION: mysql # pgsql or mysql
      DB_PASSWORD: ""
      DB_HOST: firefly-firefly-db
      DB_PORT: "3306"
      DB_NAME: firefly
      DB_USER: firefly

      # -- Set this to the name of a secret to load environment variables from. If defined, values in the secret will override values in configs
    existingSecret: ""


