{{- if and (eq .Values.storage.existingClaim "") .Values.storage.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ printf "%s-%s" (include "firefly-db.fullname" .) "storage-claim" }}
  labels:
    app: {{ template "firefly-db.name" . }}
    chart: {{ template "firefly-db.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  {{- with .Values.storage.class }}
  storageClassName: {{ . }}
  {{- end }}
  accessModes:
    - {{ .Values.storage.accessModes }}
  resources:
    requests:
      storage: {{ .Values.storage.dataSize }}
{{- end }}
