apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ template "firefly-db.fullname" . }}-db
  labels:
    app: {{ template "firefly-db.name" . }}
    chart: {{ template "firefly-db.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      pod-label: {{ template "firefly-db.fullname" . }}-pod
  template:
    metadata:
      labels:
        pod-label: {{ template "firefly-db.fullname" . }}-pod
    spec:
      containers:
      - name: {{ template "firefly-db.fullname" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        envFrom:
        - configMapRef:
            name: {{ template "firefly-db.fullname" . }}-config
        {{- if .Values.global.config.existingSecret }}
        - secretRef:
            name: {{ .Values.global.config.existingSecret }}
        {{- end }}
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        volumeMounts:
          {{- with .Values.extraVolumeMounts }}
          {{- toYaml . | nindent 8 }}
          {{- end }}
          {{ if .Values.storage.enabled }}
          {{ if .Values.image.repository | contains "mysql" }}
          - name: db-storage
            mountPath: /var/lib/mysql
            subPath: data
          {{- end }}
          {{ if .Values.image.repository | contains "postgres" }}
          - name: db-storage
            mountPath: /var/lib/postgresql/data
            subPath: data
          {{- end }}
          {{- end }}
      volumes:
        {{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{ if .Values.storage.enabled }}
        - name: db-storage
          persistentVolumeClaim:
            claimName: {{ default (printf "%s-%s" (include "firefly-db.fullname" .) "storage-claim") .Values.storage.existingClaim }}
        {{- end }}