{{- if .Values.global.config.env }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "importer.fullname" . }}
  labels:
    {{- include "importer.labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.global.config.env }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}
