  # environment variables
global:
  configs:
    RESTORE_URL: ""
    BACKUP_URL: ""
    DB_PASSWORD: "YOURDBPASSWORD"
    DB_HOST: firefly-firefly-db
    DB_PORT: "5432"
    DB_NAME: firefly
    DB_USER: firefly
    DEFAULT_LANGUAGE: "en_US"
    DEFAULT_LOCALE: "equal"
    TZ: "Europe/Amsterdam"
    TRUSTED_PROXIES: "**"


firefly-db:
  # if you set this to false it will not be installed
  enabled: true
  image:
    repository: postgres
    tag: 10-alpine
    pullPolicy: IfNotPresent

  storage:
    class: ~
    accessModes: ~  # Change as needed for your storageClass https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes
    dataSize: 1Gi

  backupSchedule: "0 3 * * *"

firefly-iii:
  # -- Set to false to not deploy Firefly III
  enabled: true

importer:
  # -- Set to false to not deploy the importer
  enabled: true
